import { Product, Collection } from './types';

// ─── Seed podaci (inicijalni katalog) ───────────────────────────────────────

export const MOCK_COLLECTIONS: Collection[] = [
  { id: 'col-1', handle: 'elektronika', title: 'Elektronika' },
  { id: 'col-2', handle: 'odeća', title: 'Odeća' },
  { id: 'col-3', handle: 'kucni-aparati', title: 'Kućni aparati' },
  { id: 'col-4', handle: 'sport', title: 'Sport i fitnes' },
  { id: 'col-5', handle: 'kozmetika', title: 'Kozmetika' },
  { id: 'col-6', handle: 'igracke', title: 'Igračke' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    handle: 'bežične-slušalice-pro',
    title: 'Bežične Slušalice Pro',
    description: 'Premium bežične slušalice sa aktivnim poništavanjem buke. Baterija traje do 30 sati. Idealne za rad od kuće i putovanje.',
    descriptionHtml: '<p>Premium bežične slušalice sa <strong>aktivnim poništavanjem buke</strong>. Baterija traje do 30 sati. Idealne za rad od kuće i putovanje.</p>',
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
      altText: 'Bežične slušalice Pro',
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80', altText: 'Bežične slušalice' },
      { url: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&q=80', altText: 'Slušalice detalj' },
    ],
    variants: [{
      id: 'var-1-1', title: 'Default', price: { amount: '4990', currencyCode: 'RSD' },
      compareAtPrice: { amount: '7990', currencyCode: 'RSD' },
      availableForSale: true, quantityAvailable: 15,
      selectedOptions: [{ name: 'Title', value: 'Default' }],
    }],
    priceRange: { minVariantPrice: { amount: '4990', currencyCode: 'RSD' }, maxVariantPrice: { amount: '4990', currencyCode: 'RSD' } },
    tags: ['elektronika', 'audio', 'bestseller'],
    vendor: 'VibeMarket',
    productType: 'Elektronika',
    availableForSale: true,
    comparisonPoints: [
      'Aktivno poništavanje buke - ne samo pasivna izolacija zvuka',
      'Baterija do 30h, drugi modeli retko prelaze 20h',
      'Udobne za višesatno nošenje na sastancima i letovima',
      'Brzo Bluetooth uparivanje bez isprekidanog zvuka',
    ],
    faqs: [
      { question: 'Da li imaju aktivno poništavanje buke?', answer: 'Da, ANC se automatski uključuje i značajno prigušuje zvuk okoline.' },
      { question: 'Koliko traje baterija?', answer: 'Do 30 sati reprodukcije uz uključen ANC, u zavisnosti od glasnoće.' },
      { question: 'Da li su kompatibilne sa iPhone i Android telefonima?', answer: 'Da, rade preko Bluetooth-a sa svim uređajima koji ga podržavaju.' },
      { question: 'Da li imaju mikrofon za pozive?', answer: 'Da, ugrađeni mikrofon je pogodan za pozive i video sastanke.' },
    ],
  },
  {
    id: 'prod-2',
    handle: 'pametni-sat-sport',
    title: 'Pametni Sat Sport X5',
    description: 'Sportski pametni sat sa GPS-om, merenjem pulsa i vodonepropusnošću do 50m. Savršen za trčanje i plivanje.',
    descriptionHtml: '<p>Sportski pametni sat sa <strong>GPS-om</strong>, merenjem pulsa i vodonepropusnošću do 50m.</p>',
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80',
      altText: 'Pametni sat Sport X5',
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80', altText: 'Pametni sat' },
    ],
    variants: [{
      id: 'var-2-1', title: 'Crna', price: { amount: '8990', currencyCode: 'RSD' },
      compareAtPrice: null,
      availableForSale: true, quantityAvailable: 8,
      selectedOptions: [{ name: 'Boja', value: 'Crna' }],
    }, {
      id: 'var-2-2', title: 'Srebrna', price: { amount: '8990', currencyCode: 'RSD' },
      compareAtPrice: null,
      availableForSale: true, quantityAvailable: 5,
      selectedOptions: [{ name: 'Boja', value: 'Srebrna' }],
    }],
    priceRange: { minVariantPrice: { amount: '8990', currencyCode: 'RSD' }, maxVariantPrice: { amount: '8990', currencyCode: 'RSD' } },
    tags: ['sport', 'pametni-sat', 'novo'],
    vendor: 'VibeMarket',
    productType: 'Sport',
    availableForSale: true,
    comparisonPoints: [
      'Ugrađen GPS - precizno prati rutu bez telefona u džepu',
      'Vodonepropusnost do 50m, može i na plivanje',
      'Neprekidno merenje pulsa tokom treninga',
      'Dostupan u crnoj i srebrnoj boji',
    ],
    faqs: [
      { question: 'Da li mogu da plivam sa satom?', answer: 'Da, vodonepropustan je do 50m i pogodan za plivanje.' },
      { question: 'Da li prati rutu trčanja bez telefona?', answer: 'Da, zahvaljujući ugrađenom GPS-u ne morate nositi telefon sa sobom.' },
      { question: 'Koje boje su dostupne?', answer: 'Crna i srebrna.' },
      { question: 'Da li meri puls tokom celog dana?', answer: 'Da, senzor pulsa radi kontinuirano, ne samo tokom treninga.' },
    ],
  },
  {
    id: 'prod-3',
    handle: 'bluetooth-zvucnik',
    title: 'Bluetooth Zvučnik Boost',
    description: 'Vodootporni Bluetooth zvučnik sa 360° zvukom i baterijom od 20 sati. Idealan za piknik i plažu.',
    descriptionHtml: '<p>Vodootporni Bluetooth zvučnik sa <strong>360° zvukom</strong> i baterijom od 20 sati.</p>',
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80',
      altText: 'Bluetooth zvučnik',
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80', altText: 'Zvučnik' },
    ],
    variants: [{
      id: 'var-3-1', title: 'Default', price: { amount: '3490', currencyCode: 'RSD' },
      compareAtPrice: { amount: '4990', currencyCode: 'RSD' },
      availableForSale: true, quantityAvailable: 23,
      selectedOptions: [{ name: 'Title', value: 'Default' }],
    }],
    priceRange: { minVariantPrice: { amount: '3490', currencyCode: 'RSD' }, maxVariantPrice: { amount: '3490', currencyCode: 'RSD' } },
    tags: ['elektronika', 'audio'],
    vendor: 'VibeMarket',
    productType: 'Elektronika',
    availableForSale: true,
    comparisonPoints: [
      '360° zvuk puni prostor, ne samo jedan pravac',
      'Vodootporan - bez brige na plaži ili pored bazena',
      'Baterija do 20 sati neprekidne muzike',
      'Kompaktan i lak za nošenje na putovanjima',
    ],
    faqs: [
      { question: 'Da li je otporan na vodu i prskanje?', answer: 'Da, kućište je vodootporno i podnosi prskanje i kišu.' },
      { question: 'Koliko dugo traje baterija?', answer: 'Do 20 sati reprodukcije na srednjoj jačini zvuka.' },
      { question: 'Da li se lako povezuje sa telefonom?', answer: 'Da, Bluetooth uparivanje traje par sekundi i pamti poslednji povezani uređaj.' },
      { question: 'Da li je pogodan za spoljnu upotrebu?', answer: 'Da, idealan je za plažu, piknik i dvorište zahvaljujući vodootpornosti.' },
    ],
  },
  {
    id: 'prod-4',
    handle: 'laptop-stend',
    title: 'Ergonomski Laptop Stend',
    description: 'Aluminijumski laptop stend sa podesivim visinom i uglom. Poboljšava držanje i smanjuje bol u vratu.',
    descriptionHtml: '<p>Aluminijumski laptop stend sa podesivim visinom i uglom.</p>',
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80',
      altText: 'Laptop stend',
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80', altText: 'Laptop stend' },
    ],
    variants: [{
      id: 'var-4-1', title: 'Default', price: { amount: '2990', currencyCode: 'RSD' },
      compareAtPrice: null,
      availableForSale: true, quantityAvailable: 31,
      selectedOptions: [{ name: 'Title', value: 'Default' }],
    }],
    priceRange: { minVariantPrice: { amount: '2990', currencyCode: 'RSD' }, maxVariantPrice: { amount: '2990', currencyCode: 'RSD' } },
    tags: ['kancelarija', 'laptop'],
    vendor: 'VibeMarket',
    productType: 'Kancelarija',
    availableForSale: true,
    comparisonPoints: [
      'Aluminijumska konstrukcija - stabilnija od plastičnih postolja',
      'Podesiva visina i ugao za idealan položaj ekrana',
      'Smanjuje bol u vratu i ramenima pri dužem radu',
      'Lagan i sklopiv za nošenje na posao ili put',
    ],
    faqs: [
      { question: 'Da li odgovara svim veličinama laptopa?', answer: 'Da, podesiv je i pristaje laptopovima od 11 do 17 inča.' },
      { question: 'Da li stend može da se sklopi za nošenje?', answer: 'Da, sklapa se u ravan oblik i staje u torbu za laptop.' },
      { question: 'Od kog materijala je napravljen?', answer: 'Od aluminijuma, stabilniji je i izdržljiviji od plastičnih alternativa.' },
      { question: 'Da li poboljšava hlađenje laptopa?', answer: 'Da, podizanjem laptopa sa podloge poboljšava se protok vazduha ispod njega.' },
    ],
  },
  {
    id: 'prod-5',
    handle: 'fitnes-narukvica',
    title: 'Fitnes Narukvica Ultra',
    description: 'Fitnes narukvica sa praćenjem sna, aktivnosti i stresa. Baterija 7 dana, AMOLED ekran.',
    descriptionHtml: '<p>Fitnes narukvica sa praćenjem sna, aktivnosti i stresa.</p>',
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80',
      altText: 'Fitnes narukvica',
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80', altText: 'Narukvica' },
    ],
    variants: [{
      id: 'var-5-1', title: 'Crna', price: { amount: '2490', currencyCode: 'RSD' },
      compareAtPrice: { amount: '3990', currencyCode: 'RSD' },
      availableForSale: true, quantityAvailable: 42,
      selectedOptions: [{ name: 'Boja', value: 'Crna' }],
    }],
    priceRange: { minVariantPrice: { amount: '2490', currencyCode: 'RSD' }, maxVariantPrice: { amount: '2490', currencyCode: 'RSD' } },
    tags: ['sport', 'fitnes', 'bestseller'],
    vendor: 'VibeMarket',
    productType: 'Sport',
    availableForSale: true,
    comparisonPoints: [
      'AMOLED ekran - oštriji i vidljiviji na suncu od LCD narukvica',
      'Baterija traje 7 dana bez punjenja',
      'Prati san, stres i aktivnost, ne samo korake',
      'Lagana za celodnevno nošenje, i tokom spavanja',
    ],
    faqs: [
      { question: 'Koliko traje baterija?', answer: 'Do 7 dana uz normalno korišćenje, u zavisnosti od broja obaveštenja.' },
      { question: 'Da li prati kvalitet sna?', answer: 'Da, analizira faze sna i prikazuje ih u pratećoj aplikaciji.' },
      { question: 'Da li je vodootporna za tuširanje?', answer: 'Otporna je na znoj i kišu; nije predviđena za ronjenje.' },
      { question: 'Da li radi sa iPhone i Android telefonima?', answer: 'Da, preko prateće aplikacije radi sa oba operativna sistema.' },
    ],
  },
  {
    id: 'prod-6',
    handle: 'wireless-punjač',
    title: 'Wireless Punjač 15W',
    description: 'Brzi bežični punjač kompatibilan sa svim Qi uređajima. Punjenje 15W za iPhone i 10W za Android.',
    descriptionHtml: '<p>Brzi bežični punjač kompatibilan sa svim Qi uređajima.</p>',
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&q=80',
      altText: 'Wireless punjač',
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&q=80', altText: 'Punjač' },
    ],
    variants: [{
      id: 'var-6-1', title: 'Default', price: { amount: '1990', currencyCode: 'RSD' },
      compareAtPrice: null,
      availableForSale: true, quantityAvailable: 67,
      selectedOptions: [{ name: 'Title', value: 'Default' }],
    }],
    priceRange: { minVariantPrice: { amount: '1990', currencyCode: 'RSD' }, maxVariantPrice: { amount: '1990', currencyCode: 'RSD' } },
    tags: ['elektronika', 'punjač'],
    vendor: 'VibeMarket',
    productType: 'Elektronika',
    availableForSale: true,
    comparisonPoints: [
      '15W za iPhone i 10W za Android - brže od standardnih 5W punjača',
      'Kompatibilan sa svim Qi uređajima, ne samo jednim brendom',
      'Bez potrebe za skidanjem tanje maskice telefona',
      'Kompaktan dizajn koji se uklapa na svaki radni sto',
    ],
    faqs: [
      { question: 'Da li radi sa maskicom na telefonu?', answer: 'Da, dok god je maskica tanja od 5mm i ne sadrži metal.' },
      { question: 'Koja je brzina punjenja?', answer: 'Do 15W za iPhone i do 10W za Android uređaje sa Qi podrškom.' },
      { question: 'Da li je potreban poseban adapter?', answer: 'Preporučuje se adapter od 18W ili jači za punu brzinu punjenja.' },
      { question: 'Da li se pregreva pri dužem korišćenju?', answer: 'Ne, ima ugrađenu zaštitu od pregrevanja i previsokog napona.' },
    ],
  },
  {
    id: 'prod-7',
    handle: 'mehanička-tastatura',
    title: 'Mehanička Gaming Tastatura',
    description: 'RGB mehanička tastatura sa Cherry MX Red tasterima. Idealna za gaming i brzo kucanje.',
    descriptionHtml: '<p>RGB mehanička tastatura sa <strong>Cherry MX Red</strong> tasterima.</p>',
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80',
      altText: 'Mehanička tastatura',
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80', altText: 'Tastatura' },
    ],
    variants: [{
      id: 'var-7-1', title: 'Default', price: { amount: '5990', currencyCode: 'RSD' },
      compareAtPrice: { amount: '8990', currencyCode: 'RSD' },
      availableForSale: true, quantityAvailable: 12,
      selectedOptions: [{ name: 'Title', value: 'Default' }],
    }],
    priceRange: { minVariantPrice: { amount: '5990', currencyCode: 'RSD' }, maxVariantPrice: { amount: '5990', currencyCode: 'RSD' } },
    tags: ['gaming', 'tastatura', 'novo'],
    vendor: 'VibeMarket',
    productType: 'Elektronika',
    availableForSale: true,
    comparisonPoints: [
      'Pravi Cherry MX Red tasteri - brži i tiši od membranskih tastatura',
      'RGB pozadinsko osvetljenje sa podesivim efektima',
      'Izdržljivost od preko 50 miliona pritisaka po tasteru',
      'Odziv dovoljno brz za konkurentno igranje',
    ],
    faqs: [
      { question: 'Kakvi su Cherry MX Red tasteri?', answer: 'Linearni su i tihi, sa nižim otporom pritiska - pogodni za brzo igranje i kucanje.' },
      { question: 'Da li se RGB osvetljenje može podesiti?', answer: 'Da, boje i efekti se menjaju preko kombinacija tastera ili pratećeg softvera.' },
      { question: 'Da li je tastatura žičana ili bežična?', answer: 'Žičana je, radi stabilne konekcije bez kašnjenja.' },
      { question: 'Da li je pogodna i za kucanje, ne samo igranje?', answer: 'Da, Cherry MX Red taster je tih i udoban i za dugotrajno kucanje.' },
    ],
  },
  {
    id: 'prod-8',
    handle: 'web-kamera-4k',
    title: 'Web Kamera 4K Ultra HD',
    description: '4K web kamera sa autofokusom i redukcijom buke mikrofona. Savršena za video pozive i streaming.',
    descriptionHtml: '<p>4K web kamera sa autofokusom i redukcijom buke mikrofona.</p>',
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=600&q=80',
      altText: 'Web kamera 4K',
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=600&q=80', altText: 'Kamera' },
    ],
    variants: [{
      id: 'var-8-1', title: 'Default', price: { amount: '6990', currencyCode: 'RSD' },
      compareAtPrice: null,
      availableForSale: true, quantityAvailable: 9,
      selectedOptions: [{ name: 'Title', value: 'Default' }],
    }],
    priceRange: { minVariantPrice: { amount: '6990', currencyCode: 'RSD' }, maxVariantPrice: { amount: '6990', currencyCode: 'RSD' } },
    tags: ['elektronika', 'kamera', 'streaming'],
    vendor: 'VibeMarket',
    productType: 'Elektronika',
    availableForSale: true,
    comparisonPoints: [
      'Snima u pravom 4K - oštrije od standardnih HD kamera',
      'Autofokus prati pokret bez zamućenja',
      'Mikrofon sa redukcijom buke za jasan zvuk na pozivima',
      'Plug-and-play - bez instalacije dodatnog softvera',
    ],
    faqs: [
      { question: 'Da li zahteva instalaciju drajvera?', answer: 'Ne, radi po plug-and-play principu preko USB porta.' },
      { question: 'Da li snima u 4K rezoluciji?', answer: 'Da, podržava snimanje i strimovanje u 4K Ultra HD rezoluciji.' },
      { question: 'Da li ima ugrađen mikrofon?', answer: 'Da, sa redukcijom buke iz okoline za čistiji zvuk.' },
      { question: 'Da li se može postaviti na monitor ili tronožac?', answer: 'Da, dolazi sa klipsom za monitor i navojem za tronožac.' },
    ],
  },
];
